#include "z64audio.h"

// TODO move
#ifndef NO_REORDER
#ifdef __GNUC__
#define NO_REORDER __attribute__((no_reorder))
#else
#define NO_REORDER
#endif
#endif

#include "assets/audio/soundfonts/Soundfont_0.h"
#include "assets/audio/soundfonts/Soundfont_1.h"
#include "assets/audio/soundfonts/Soundfont_2.h"
#include "assets/audio/soundfonts/Soundfont_3.h"
#include "assets/audio/soundfonts/Soundfont_4.h"
#include "assets/audio/soundfonts/Soundfont_5.h"
#include "assets/audio/soundfonts/Soundfont_6.h"
#include "assets/audio/soundfonts/Soundfont_7.h"
#include "assets/audio/soundfonts/Soundfont_8.h"
#include "assets/audio/soundfonts/Soundfont_9.h"
#include "assets/audio/soundfonts/Soundfont_10.h"
#include "assets/audio/soundfonts/Soundfont_11.h"
#include "assets/audio/soundfonts/Soundfont_12.h"
#include "assets/audio/soundfonts/Soundfont_13.h"
#include "assets/audio/soundfonts/Soundfont_14.h"
#include "assets/audio/soundfonts/Soundfont_15.h"
#include "assets/audio/soundfonts/Soundfont_16.h"
#include "assets/audio/soundfonts/Soundfont_17.h"
#include "assets/audio/soundfonts/Soundfont_18.h"
#include "assets/audio/soundfonts/Soundfont_19.h"
#include "assets/audio/soundfonts/Soundfont_20.h"
#include "assets/audio/soundfonts/Soundfont_21.h"
#include "assets/audio/soundfonts/Soundfont_22.h"
#include "assets/audio/soundfonts/Soundfont_23.h"
#include "assets/audio/soundfonts/Soundfont_24.h"
#include "assets/audio/soundfonts/Soundfont_25.h"
#include "assets/audio/soundfonts/Soundfont_26.h"
#include "assets/audio/soundfonts/Soundfont_27.h"
#include "assets/audio/soundfonts/Soundfont_28.h"
#include "assets/audio/soundfonts/Soundfont_29.h"
#include "assets/audio/soundfonts/Soundfont_30.h"
#include "assets/audio/soundfonts/Soundfont_31.h"
#include "assets/audio/soundfonts/Soundfont_32.h"
#include "assets/audio/soundfonts/Soundfont_33.h"
#include "assets/audio/soundfonts/Soundfont_34.h"
#include "assets/audio/soundfonts/Soundfont_35.h"
#include "assets/audio/soundfonts/Soundfont_36.h"
#include "assets/audio/soundfonts/Soundfont_37.h"
#include "assets/audio/soundfonts/Soundfont_38.h"
#include "assets/audio/soundfonts/Soundfont_39.h"
#include "assets/audio/soundfonts/Soundfont_40.h"

// TODO we could avoid atblgen for the header by having the user include soundfont headers generated by sfc, containing all the important defines
// However this is prone to going out of sync wrt the soundfont indices which must inevitably be recorded somewhere for the sequence font table.
// We could just count the numbers anyway, would save some work in atblgen that's mostly just a cut-down version of what sfc is already doing.

// Symbol definition

extern AudioTable gSoundFontTable;
#pragma weak gSoundFontTable = sSoundFontTableHeader

// Externs for table

#define DEFINE_SOUNDFONT(name, medium, cachePolicy, sampleBankNormal, sampleBankDD, nInstruments, nDrums, nSfx)   \
    extern u8 name##_Start[]; extern u8 name##_Size[];

#include "audio/soundfont_table.h"

#undef DEFINE_SOUNDFONT

// Table header

NO_REORDER AudioTableHeader sSoundFontTableHeader = {
    // The table contains the number of samplebanks, count them with the preprocessor
#define DEFINE_SOUNDFONT(name, medium, cachePolicy, sampleBankNormal, sampleBankDD, nInstruments, nDrums, nSfx) \
    1+

#include "audio/soundfont_table.h"

#undef DEFINE_SOUNDFONT
    0,

    0,
    0x00000000,
    { 0, 0, 0, 0, 0, 0, 0, 0 },
};

// Table body

NO_REORDER AudioTableEntry sSoundFontTableEntries[] = {
#define DEFINE_SOUNDFONT(name, medium, cachePolicy, sampleBankNormal, sampleBankDD, nInstruments, nDrums, nSfx) \
    { (u32)name##_Start, (u32)name##_Size, (medium), (cachePolicy), ((sampleBankNormal) << 8) | (sampleBankDD), \
      ((nInstruments) << 8) | (nDrums), (nSfx) },

#include "audio/soundfont_table.h"

#undef DEFINE_SOUNDFONT
};
